### ISSUE TITLE
TypeError: _build_package_finder() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/python#96]
```
Traceback (most recent call last):
  File "/usr/src/app/entrypoint.py", line 10, in <module>
    collect()
  File "/usr/src/app/collect.py", line 26, in collect
    output['manifests'][manifest.filename] = { 'current': { 'dependencies': manifest.dio_dependencies() } }
  File "/usr/src/app/models.py", line 89, in dio_dependencies
    'available': [{'name': x} for x in get_available_versions_for_dependency(dep.key, dep.specs)],
  File "/usr/src/app/models.py", line 178, in get_available_versions_for_dependency
    finder = list_command._build_package_finder(options, index_urls, session)
TypeError: _build_package_finder() takes 3 positional arguments but 4 were given
```

Relevant job: https://app.dependencies.io/j/1d118ccd-d94f-4072-97eb-eb4dfcb75774

This is due to a change in the internal `ListCommand._build_package_finder` method with https://github.com/pypa/pip/commit/cab7316e2b6f994d95527c0577c14f6ae2164126 in pip v19.2.

**Comment by davegaeddert** [comment]
Thanks @Harmon758 (especially for the link to the pip change). I got notice from TravisCI that this failed but didn't have time to look yet. Just pushed a fix.

Somewhat related... I've been pushing towards a new version of dependencies.io to solve some of the long standing questions/problems. It will run directly in your existing CI setup (CircleCI, TravisCI, etc.) instead of us trying to replicate those environments and system requirements elsewhere. Anyway I mention it because the new version of the python support doesn't use this internal API anymore ;). If you're interested in testing this out at all, you can drop an email address here: https://www.dependencies.io/
